# Generated by Django 5.1.4 on 2024-12-27 13:12

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Recipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField(blank=True, null=True)),
                ('ingredients', models.TextField()),
                ('instructions', models.TextField()),
                ('category', models.CharField(choices=[('Dessert', 'Dessert'), ('Main Course', 'Main Course'), ('Appetizer', 'Appetizer'), ('Breakfast', 'Breakfast'), ('Vegetarian', 'Vegetarian')], max_length=50)),
                ('preparation_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('cooking_time', models.PositiveIntegerField(help_text='Time in minutes')),
                ('servings', models.PositiveIntegerField()),
                ('created_date', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recipes', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
